### ISSUE TITLE
decide on the right empty response

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/metadata_api#1]
We have to decide what should be returned to the users when there are no results.  This is separate from an error message for bad queries.

I believe that right now we have "[]" and we considered switching to "{}"

Here's some discussion: 
https://stackoverflow.com/questions/21120999/representing-null-in-json

**Comment by msalganik** [comment]
Rather than empty response, we might return something that says no response.  This is what someone told me was best practice (I'm not sure).  That person also recommend this vignette: https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html

**Comment by mayaprinceton** [comment]
From my experience, no json response implies an error. I'm not entirely sure what is best practice here. For now, I changed empty to return "{}". Should I change this to something else?

**Comment by msalganik** [comment]
@mayaprinceton  to be honest I don't know.  But @ifellows might know.  @ifellows what do you think is the right response for a query to the API that returns nothing? (cc @atkindel)

**Comment by ifellows** [comment]
From the APIs perspective, it is not an error. I would suggest {} if the api is returning an object and [] if it is an array

**Comment by msalganik** [comment]
I just talked to @atkindel and we agree {} for an empty response.

Now I'm going to reassign to @atkindel because he's working on it with the web app.
