### ISSUE TITLE
multiple data files?

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/metadata_api#12]
@atkindel There are metadata files in the main directory, which appear to be older than the file in the data directory.  If the data directory file is the one we are using, can we remove the ones from the main directory?  Also, the README recommends the tab delimited file, but the file in the data folder is .csv.  Is the README stale?

**Comment by vineetbansal** [comment]
There's now only one csv file in the ffmeta/data folder. If we agree that there's always going to be one csv file for ffmetadata (along with other potential files in the future), then perhaps we don't need to suffix the YYYYMMDD date to it, we just call it ffmetadata.csv, and let the git machinery help us in tracking changes to the files.

**Comment by msalganik** [comment]
@vineetbansal not everyone on the team is totally comfortable with git so I'm not sure if that is a good solution.  Can we stick with the dates for now?

But I think a better long term solution is some kind of versioning system (https://www.jvandemo.com/a-simple-guide-to-semantic-versioning/) for the data file, the API, and the web app.

**Comment by vineetbansal** [comment]
This issue was moved to fragilefamilieschallenge/metadata_app#56
