### ISSUE TITLE
Travis Integration

### ISSUE THREAD

**Issue by vineetbansal** [fragilefamilieschallenge/metadata_api#16]
The cleanest way to incorporate tests into the CI process is to use Travis (available to all github users at https://travis-ci.org for public repos, travis-ci.com for private repos) Usually one can integrate a repo with Travis by making the repository 'visible' to Travis (by logging into Travis with your GitHub account, and flicking a switch next to the repo name under question). I'm not seeing this repo under my account, I think because I'm not listed as an 'owner' for this repo.

If someone with owner permissions can make this association, it'll set up a Travis container where project dependencies can be installed. The container will fire up automatically and tests run automatically every time a commit is made (based on a .travis.yml in the repo base folder and a 'tests' folder, both of which I can add) and we can then get going with unit tests.

**Comment by msalganik** [comment]
@vineetbansal Great.  I like travis.  I've changed your permissions.  If this works for you, please close the issue.

**Comment by vineetbansal** [comment]
Seems to work. Thanks!
