### ISSUE TITLE
Syntax error when trying to run docker locally

### ISSUE THREAD

**Issue by thartshorne** [fragilefamilieschallenge/metadata_api#19]
I am getting the following error when I try and create a local version of the API code using Docker:

![image](https://user-images.githubusercontent.com/10812643/38640570-a8d1c780-3da2-11e8-9921-40251059c8cb.png)

The line of code this seems to be pointing to is:
# Configure application
application.config.from_envvar('APP_CONFIG', silent=True)

Here is a link from Flask which I think to be relevant: http://flask.pocoo.org/docs/0.12/config/#configuring-from-files

I'm just not familiar enough with the command line coding to be able to debug this myself. Is there a simple solution that I am missing?

Thanks

**Comment by msalganik** [comment]
@thartshorne I've assigned this to @atkindel.  I think he should be able to help.

**Comment by thartshorne** [comment]
This is likely the issue. I downloaded the file from an email that Alex sent me with this as the attachment.

**Comment by thartshorne** [comment]
Curiously, I did the same process for the app and did not have this same issue.

**Comment by atkindel** [comment]
@thartshorne It sounds like this is resolved -- let me know if OK to close this issue

**Comment by thartshorne** [comment]
@atkindel Yup! All resolved. Thanks for the help @vineetbansal
