### ISSUE TITLE
Revise README.md

### ISSUE THREAD

**Issue by atkindel** [fragilefamilieschallenge/metadata_api#37]
Resolving issue #14 suggests that the current README.md is out of date with the current API design

**Comment by msalganik** [comment]
Thanks @atkindel.  I've assigned this to @vineetbansal

**Comment by vineetbansal** [comment]
Updated README. Modified examples and their order to be clearer. Probably better for someone to read through to make sure it's clear enough.

**Comment by msalganik** [comment]
Thanks @vineetbansal.  That looks pretty clear to me.
