### ISSUE TITLE
localMetadataAPI shouldn't exist

### ISSUE THREAD

**Issue by vineetbansal** [fragilefamilieschallenge/metadata_api#38]
The purpose of localMetadataAPI.py is to read data from a csv file, and provide functions on top of it. This seems to me to be not needed for 3 reasons:

1. If the authoritative source of the data is the database (which we're saying it is), then an alternative way to access data is potentially very confusing to the user.
2. Which file (out of several that might be present in the 'data' folder) is the user supposed to trust? Is it always guaranteed that the results from the web will match the latest csv file that one finds locally?
3. A csv file is inherently such a simple format that one should not have to write functions on top of it just to provide access to it. If functions are needed, then it's an indication that the csv file is not being generated in a usable way, and that's the problem we should address.

If people agree, then localMetadataAPI.py should go.

**Comment by msalganik** [comment]
@vineetbansal I agree.  localMetadataAPI.py made sense at one time, but how we are thinking about the project has changed.  

Please get rid of this file and remove any mention of it from the readme.  We can always resurrect it if someone else wants to make a strong case for it.

**Comment by vineetbansal** [comment]
Thanks @msalganik  - I've deleted the file. There are no mentions of it in the README.
