### ISSUE TITLE
/filter and /search - potentially confusing; responsibilities overlap

### ISSUE THREAD

**Issue by vineetbansal** [fragilefamilieschallenge/metadata_api#39]
It seems to me that everything that can be done in /search and also be done in /filter, and vice versa, by changing the format of the query. For example, the following are equivalent:

/search?fieldName=label&query=CPS
/filter?label=CPS

Both implement a fuzzy search using sql 'like'.
As such, one of them can be dropped. I like keeping the '/filter' endpoint since its syntax is shorter. The Python/R code calling the api can simply drop the implementation of one of the calls.

**Comment by msalganik** [comment]
I'm not 100% percent sure that this is true.  I think we talked about this a long time ago, when we were making these, but I don't remember.  Sorry.  In any case, why drop one of these now if we are going to refactor the whole "search" functionality soon?

**Comment by vineetbansal** [comment]
@msalganik - sounds good. I agree that this will cease to be a problem in a few weeks anyway.
