### ISSUE TITLE
update README with some examples

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/metadata_api#7]
Nice to have some simple examples there

**Comment by thartshorne** [comment]
Just for clarification, we are looking to add examples of the functions? E.g an example of how the "search" function works, with arguments and the returned results?

**Comment by msalganik** [comment]
I'm imagining a few example queries with the reply that would come back.  I'd also recommend looking at other API documentation to see how they have examples.

**Comment by vineetbansal** [comment]
Hi Tom..if/when my pull request is accepted, or even otherwise, you might want to do this on a markdown version of README, not a plain text file, so you have more flexibility in formatting code blocks etc. for examples.

**Comment by msalganik** [comment]
Good point @vineetbansal.  Sorry that I forgot to mention that @thartshorne.

**Comment by msalganik** [comment]
https://github.com/fragilefamilieschallenge/metadata_api/pull/21
